### ISSUE TITLE
Image Basepaths - Missing basepath in new_image_object

### ISSUE THREAD

**Issue by ghost** [FuchsEDV/Thrixty#1]
The basepath is missing in the "source" property of the "new_image_object" object on line 648 and 677.
As a result the basepath has to be added manually to each item in the filelist.txt to get the correct filepath.

 My suggestion:
`source: this.settings.basepath + image_paths[i]`

**Comment by FuchsEDV** [comment]
The basepath property is intended for finding the Filelist.txt only, while your suggestion is aimed at the result of the filelist parsing.
Your filelist is supposed to have the full address to your pictures.

The reasons behind this are of historical nature, as our Worktable Software is exporting filelists with full absolute paths.

I am actually intending to upgrade the filelist format itself. I would also like to have a basepath property in there.
For now you need to change the paths in the file though - sorry.

Thank you for our first ticket. ;)

**Comment by ghost** [comment]
You are welcome. :)

> The reasons behind this are of historical nature, as our Worktable Software is exporting filelists with full absolute paths.

Our worktable software is exporting the filelists with relative paths. Are we doing something wrong or do we have an old version? I believe we are using version 4.002 of the worktable software.

**Comment by FuchsEDV** [comment]
Go to the export dialog. You are entering it when you are about to export an object.
In the top bar you go to "Ablage" => "Accounts verwalten".

You will see a list of your export settings; the setting "Bild URL" ist the one you are looking for.
It is the path to the files, that is being prepended to the filelist entries.

We set it to "http://www.360shots.de/360grad-bilder" for the exports to our website.
Just type in something similar to this and export anew - that should solve it.

Alternatively you could write a little programm to alter your existing filelists, when you would waste too much time on reexporting.
Its a simple matter of splitting upon <code>,</code>, prepending your path to the existing values (there are <code>'</code> around the paths) and glueing the array back together.

**Comment by ghost** [comment]
Ah ok... All those settings were not set. Thanks a lot.
